### ISSUE TITLE
wildcard import `mycroft_bus_client.util` not viable

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-bus-client#18]
```
Apr 20 20:50:34 ovos ovos-systemd-voice[913]: 2023-04-20 20:50:34.547 - OVOS - ovos_utils.configuration:<module>:52 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
Apr 20 20:50:35 ovos ovos-systemd-voice[913]: Traceback (most recent call last):
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "/usr/libexec/ovos-systemd-voice", line 19, in <module>
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:     from ovos_dinkum_listener.__main__ import main
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "/usr/local/lib/python3.9/dist-packages/ovos_dinkum_listener/__main__.py", line 26, in <module>
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:     from ovos_bus_client import Message, MessageBusClient
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "/usr/local/lib/python3.9/dist-packages/ovos_bus_client/__init__.py", line 14, in <module>
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:     from ovos_bus_client.client.client import MessageBusClient
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "/usr/local/lib/python3.9/dist-packages/ovos_bus_client/client/__init__.py", line 14, in <module>
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:     from .client import MessageBusClient, MessageWaiter, MessageCollector
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "/usr/local/lib/python3.9/dist-packages/ovos_bus_client/client/client.py", line 2, in <module>
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:     from ovos_bus_client.util import create_echo_function
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "/usr/local/lib/python3.9/dist-packages/ovos_bus_client/util/__init__.py", line 18, in <module>
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:     from mycroft_bus_client.util import *
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "<frozen importlib._bootstrap>", line 1053, in _handle_fromlist
Apr 20 20:50:35 ovos ovos-systemd-voice[913]:   File "<frozen importlib._bootstrap>", line 1049, in _handle_fromlist
Apr 20 20:50:35 ovos ovos-systemd-voice[913]: TypeError: Item in mycroft_bus_client.util.__all__ must be str, not type
```

**Comment by emphasize** [comment]
oh, that was fixed. dinkum is pulling an older version
